### ISSUE TITLE
Repo missing code

### ISSUE THREAD

**Issue by tor0405** [FredrikAugust/git-ops-rs#1]
Tried to run npm install but got an error..

**Comment by FredrikAugust** [comment]
I'm terribly sorry, @tor0405.
Could you please try `yarn` now?

**Comment by FredrikAugust** [comment]
This has been fixed in the last commit [a271208](https://github.com/FredrikAugust/git-ops-rs/commit/a271208afe34ef8c67c26113840aa7d0bfc6ad03).
